HYPO_SEARCH_API = 'HYPO_SEARCH_API'
HYPO_AUTH_TOKEN = 'HYPO_AUTH_TOKEN'

config = {
    # 'HYPO_SEARCH_API': 'https://api.hypothes.is/search',
    'HYPO_SEARCH_API': 'http://localhost:5000/api/search',
    'HYPO_AUTH_TOKEN': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJpc3MiOiJub3N1Y2hpZCIsInVzZXJJZCI6ImFjY3Q6dWp2YXJpQGxvY2FsaG9zdCIsImNvbnN1bWVyS2V5Ijoibm9zdWNoaWQiLCJleHAiOjE0Mjc4OTQ5MDQsInR0bCI6MzYwMCwiaXNzdWVkQXQiOiIyMDE1LTA0LTAxVDEyOjI4OjI0IiwiaWF0IjoxNDI3ODkxMzA0LCJzdWIiOiJhY2N0OnVqdmFyaUBsb2NhbGhvc3QifQ.b9mWnn8swW42gmcnVO3YKoTdVFw2a2pRMSgoe2fH0fI'
}